In [ ]:
import numpy as np

L = 5

# LxL 크기의 행렬을 반환하는 함수
def index_matrix(L):
    return np.arange(L**2).reshape((L, L))

# 1. 랜덤으로 -1 또는 1을 가지는 LxL 크기의 스핀 행렬을 반환하는 함수
def S(L):
    return np.random.choice([-1, 1], size=(L, L))

# 2. 특정 인덱스의 스핀과 그 이웃들의 위치를 반환하는 함수
def neighbor(number):
    i, j = divmod(number, L)  # number를 L로 나눈 몫과 나머지를 구함
    neighbors_index = [(i, (j-1)%L), (i, (j+1)%L), ((i-1)%L, j), ((i+1)%L, j)]  # 왼쪽, 오른쪽, 위, 아래 이웃의 위치 계산
    return [(i*L+j) for i, j in neighbors_index]  # 이웃들의 위치를 1차원 인덱스로 변환하여 반환

# 특정 인덱스의 스핀과 그 이웃들의 값(스핀)을 반환하는 함수
def neighbor_value(number):
    i, j = divmod(number, L)
    neighbors_index = [(i, (j-1)%L), (i, (j+1)%L), ((i-1)%L, j), ((i+1)%L, j)]
    result = []
    for idx in [(i*L+j) for i, j in neighbors_index]:
        result.append(spin_matrix[int(idx//L)][int(idx%L)])
    return result

# 3. 주어진 스핀 행렬의 에너지를 계산하는 함수
def E(spin_matrix):
    energy = 0
    for i in range(L**2):
        neighbors = neighbor(i)  # 현재 스핀의 이웃들의 인덱스를 가져옴
        neighbor_right_and_below = [neighbors[1], neighbors[3]]  # 오른쪽과 아래쪽 이웃의 인덱스만 사용
        for neighbor_index in neighbor_right_and_below:
            if spin_matrix[i//L][i%L] == spin_matrix[neighbor_index//L][neighbor_index%L]:
                energy -= 1  # 인접한 스핀이 같으면 에너지 감소
            else:
                energy += 1  # 인접한 스핀이 다르면 에너지 증가
    return energy

# 각 함수를 이용하여 결과를 출력
index_matrix = index_matrix(L)
spin_matrix = S(L)
n = 9

print(f'(-)\n인덱스 행렬:\n{index_matrix}\n')
print(f'(1)\n랜덤 생성된 스핀 행렬 (크기 {L}x{L}):\n{spin_matrix}\n')
print(f'(2)\n{n} 번째 스핀의 이웃들의 위치 인덱스 (1차원 배열로 변환):\n{neighbor(n)}\n')
print(f'(-)\n{n} 번째 스핀의 이웃들의 값 (스핀):\n{neighbor_value(n)}\n')
print(f'(3)\n계산된 전체 에너지 E:\nE = {E(spin_matrix)}')

(-)
인덱스 행렬:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]

(1)
랜덤 스핀 행렬:
[[-1 -1  1  1  1]
 [-1 -1 -1  1  1]
 [ 1 -1  1  1  1]
 [-1  1 -1 -1 -1]
 [ 1 -1  1 -1  1]]

(2)
9 번째 스핀의 이웃들의 위치:
[left, right, above, below]
[8, 5, 4, 14]

(-)
9 번째 스핀의 이웃들의 값:
[left, right, above, below]
[1, -1, 1, 1]

(3)
E = 2
